version: '3.0'
services:
  postgres:
    restart: 'always'
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=hs-db"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    volumes:
      - /tmp/postgresdata:/var/lib/postgresql/data
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
  hs-app:
    restart: 'always'
    ports:
      - '9000:80'
    environment:
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_HOST=postgres"
    build:
      context: .
      dockerfile: Dockerfile
  e2e:
    image: cypress
    build: ./e2e
    container_name: cypress
    depends_on:
      - hs-app
    environment:
      - CYPRESS_baseUrl=http://hs-app
    command: npx cypress run
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.config.js:/app/cypress.config.js
