    version: 2.1
    jobs:
      build:
        working_directory: ~/cci-hs-app # directory where steps will run
        docker:
          - image: clojure:tools-deps-alpine
        environment:
          JVM_OPTS: -Xmx3200m # limit the maximum heap size to prevent out of memory errors
        steps:
          - checkout
          - restore_cache:
              key: hs-app-{{ checksum "deps.edn" }}
          # - run: lein deps
          - save_cache:
              paths:
                - ~/.m2
              key: hs-app-{{ checksum "deps.edn" }}
          - run: clojure -T:build uber
          - persist_to_workspace:
              root: ~/cci-hs-app
              paths:
                - target
    workflows:
      version: 2.1
      build:
        jobs:
          - build
